# Generated by Django 3.2.12 on 2022-03-30 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='content',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_image', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='option_1',
            field=models.CharField(help_text='Indices for Nicotine & Grammage', max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='option_2',
            field=models.CharField(help_text='Product classification', max_length=350, null=True),
        ),
    ]
