# Generated by Django 3.2.12 on 2022-03-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20220330_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='option_2',
        ),
        migrations.AddField(
            model_name='product',
            name='link_target',
            field=models.CharField(blank=True, choices=[('_self', 'Open in same window'), ('_blank', 'Open in new window'), ('_parent', 'Delegate to parent'), ('_top', 'Delegate to top')], default='', max_length=255, verbose_name='Link target'),
        ),
    ]
