# Generated by Django 3.2.12 on 2022-03-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20220330_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='link_target',
        ),
        migrations.AlterField(
            model_name='product',
            name='option_1',
            field=models.CharField(blank=True, choices=[('0%', 'Puff 0%'), ('2%', 'Puff 2%'), ('50g', 'Hookah 50g'), ('200g', 'Hookah 200g')], default='', max_length=255, verbose_name='Indices for Nicotine & Grammage'),
        ),
    ]
