# Generated by Django 3.2.12 on 2022-03-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20220330_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='option_2',
            field=models.CharField(blank=True, choices=[('400', 'Puff 400'), ('600', 'Puff 600'), ('1000', 'Puff 1000'), ('2000', 'Puff 2000')], default='', max_length=255, verbose_name='Indices for Nicotine & Grammage'),
        ),
    ]
