# Generated by Django 3.2.12 on 2022-03-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_option_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='option_2',
            field=models.CharField(blank=True, choices=[('400', 'Puff 400'), ('600', 'Puff 600'), ('1000', 'Puff 1000'), ('2000', 'Puff 2000'), ('classic', 'UMBRA Classic'), ('intense', 'UMBRA Intense')], default='', max_length=255, verbose_name='Choose category'),
        ),
    ]
