# Generated by Django 3.2.12 on 2022-04-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_product_main_image_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='option_3',
            field=models.CharField(blank=True, choices=[('solo', 'Solo flavor'), ('mix', 'Mix flavor')], default='', max_length=255, verbose_name='Choose mix or solo hookah flavor'),
        ),
    ]
