# Generated by Django 3.2.12 on 2022-04-21 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_option_3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='option_3',
        ),
    ]
